{% set name = "intermol" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shirtsgroup/InterMol/archive/v{{ version }}.tar.gz
  sha256: a3065133ba16585a5db3807466a36242d191156525c33079cf46a97cedcfe835

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - parmed
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - intermol
    - intermol.tests
    - intermol.gromacs
    - intermol.amber
    - intermol.lammps
    - intermol.desmond

about:
  home: https://github.com/shirtsgroup/InterMol
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Conversion tool for molecular simulations
  description: Conversion tool for molecular simulations
  dev_url: https://github.com/shirtsgroup/InterMol

extra:
  recipe-maintainers:
    - mattwthompson
